version: "2"
services:
  app-simplest:
    image: alpine
    container_name: 'your-simplest-app'
    # that the important thing
    volumes_from:
      - container:simplest-sync:rw # will be mounted on /var/www
    command: ['watch', '-n3', 'cat /var/www/index.html']

# that the important thing
volumes:
  simplest-sync:
    external: true
