# This is our production compose file - not changed for docker-sync or similar

version: "2"
services:
  app-unison-dualside:
    image: alpine
    container_name: 'your-app-unison-dualside'
    command: ['watch', '-n3', 'cat /var/www/index.html']
